source 'https://rubygems.org'

gem 'sinatra'

gem 'sqlite3-ruby'
gem 'dm-core'
gem 'do_sqlite3'
gem 'dm-sqlite-adapter'
gem 'dm-timestamps'
gem 'dm-validations'
gem 'dm-migrations'
gem 'sinatra-reloader'
gem 'slugify'
gem 'will_paginate'
gem 'will_paginate-bootstrap'
gem 'dm-aggregates'
gem 'sitemap_generator'

gem 'sinatra-flash'
gem 'cloudinary'
gem 'builder'
gem 'mailgun-ruby'