gem install sinatra
gem install sqlite3-ruby
gem install dm-core
gem install do_sqlite3
gem install dm-sqlite-adapter
gem install dm-timestamps
gem install dm-validations
gem install dm-migrations
gem install sinatra-reloader
gem install slugify